import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Colors } from "../../utils/Colors";
const {width, height} = Dimensions.get('screen');

export const styles = StyleSheet.create({
    body: {
        flex: 1,
        flexDirection: 'column',
        backgroundColor: Colors.SecondColor,
        position: 'relative',
    },
    header_footer: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    buton_clear: {
        width: 32,
        height: 40,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    buton_input: {
        borderRadius: 15,
        backgroundColor: Colors.ColorInput,
        width: width - 90,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 14,
        height: 40,
        ...Colors.BoxShadow,
    },
    buton_input_max: {
        borderRadius: 15,
        backgroundColor: Colors.ColorInput,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 14,
        height: 40,
        ...Colors.BoxShadow,
    },
    buton_input_text: {
        paddingHorizontal: 6,
        fontSize: 15,
        color: 'rgba(203, 217, 255, 0.6)',
    },
    panel_title: {
        fontSize: 18,
        marginTop: 10,
        marginBottom: 20,
    },
    coll: {
        marginTop: Platform.OS === 'ios' ? 35 : 16,
        width: '100%',
        position: 'absolute',
        zIndex: 1000,
        paddingHorizontal: 20,
    },
    go_back: {
        width: 51,
        height: 51,
        borderRadius: 100,
        backgroundColor: Colors.FirstColor,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    header_search: {
        marginTop: Platform.OS === 'ios' ? 35 : 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    map: {
        // position: 'absolute',
        // top: 0,
        // left: 0,
        // right: 0,
        // bottom: 0,
        // backgroundColor: '#000',
        flex: 1,
    },
    footer: {
        width: width,
        height: 1000,
        paddingHorizontal: 20,
        flexDirection: 'column',
        // alignItems: 'center',
        backgroundColor: Colors.FirstColor,
        borderTopStartRadius: 20,
        borderTopEndRadius: 20,
    },
    panel_header: {
        paddingTop: 12,
        width: '100%',
        paddingBottom: 12,
        marginBottom: 2,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    block_hr: {
        width: 37,
        height: 4,
        backgroundColor: Colors.ColorIcon,
        borderRadius: 100,
    },
    scrollView: {
        zIndex: 0,
        width: '100%',
        paddingBottom: 120,
        // paddingHorizontal: 20,
    },
    block: {
        width: '100%',
        padding: 20,
        backgroundColor: Colors.FirstColor,
        ...Colors.BoxShadow,
        borderRadius: 20,
        marginBottom: 20,
    },
    block_set: {
        width: '100%',
        paddingTop: 20,
        paddingLeft: 20,
        paddingBottom: 20,
        backgroundColor: Colors.FirstColor,
        ...Colors.BoxShadow,
        borderRadius: 20,
        marginBottom: 20,
    },
    block_opac: {
        width: '100%',
        marginBottom: 20,
    },
    block_local: {
        width: '100%',
        padding: 20,
        paddingLeft: 0,
        backgroundColor: Colors.FirstColor,
        ...Colors.BoxShadow,
        borderRadius: 20,
        marginBottom: 20,
    },
    hr: {
        width: '100%',
        height: 1,
        backgroundColor: Colors.ColorIcon,
        opacity: 0.2,
    },
});